/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f9538a30-a4a6-4802-b5f2-bab75775e709",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lPggbAmhL",
    "aws_user_pools_web_client_id": "432cne2m1eli7nq01medh8p4t4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://n4hgvvuc75g6henrxylgsphsp4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ujaoepkfi5bxfdfz3vyvq25sfy",
    "aws_user_files_s3_bucket": "picx9a655ad2f36f42d4a7ead646953ddaed130337-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
